---
name: deploy WS server
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      - name: BUILD and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/dockerfile.ws
          push: true
          tags: shikhar0895/ws:${{ github.sha }}
      - name: Deploy frontend to the VM
        run: >
          echo "${{secrets.EC2_DEV_SERVER_PRIVKEY}}" > ssh_key && chmod 700 ssh_key
          ssh -o StrictHostKeyChecking=no -i ssh_key ubuntu@ec2-43-204-39-51.ap-south-1.compute.amazonaws.com -t "docker pull shikhar0895/ws:${{github.sha}} && docker stop ws-server && docker rm -f ws-server && docker run --name ws-server -d -e DATABASE_URL=${{DATABASE_URL}} -e PORT=8080 -p 8080:8080 shikhar0895/ws:${{github.sha}}"
